description: "Example run configuration"
tasks:
  - description: "Process Crossref data file"
    profile: "sample_configs/crossref_profile.json"
    input_dir: "sample_inputs/crossref"

  - description: "Process OpenAlex data file"
    profile: "sample_configs/openalex_profile.json"
    input_dir: "sample_inputs/openalex"